spring:
  datasource:
    url: jdbc:mysql://localhost:3306/excel_project_db?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#logging:
#  level:
#    org.springframework: DEBUG
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
server:
  port: 8088